### ISSUE TITLE
template .gfx and .txt files

### ISSUE THREAD

**Issue by ryanfantus** [SnakeManPMC/linux-pmcstat#1]
Hey there! I was trying to build and use this recently and noticed there are a lot of files mentioned which don't exist, seemingly template files (blah.1.gfx type stuff). Do you have these anywhere that I can snag? I have everything built and want to see it function as intended. Thanks!

**Comment by SnakeManPMC** [comment]
Hi there. Wow this is a blast from the past ;)

Just went through my age old Linux C coding directories and found pmcstat / pmctop dirs, in there was "pmctop.1.gfx/.txt" files one through eleven. I have uploaded them: https://www.pmc1984.com/misc/pmcstat.pmctop.daydream.bbs.door.templates.2022-12-26.7z

Let me know if those were the correct ones and if anything was missing.

Currently I don't think I have the "original" git dir for my 1990s Linux C tools anywhere so would take some doing to officially add them into this repository, but I wrote a TODO issue for myself so maybe one day it gets done :)

**Comment by ryanfantus** [comment]
Woot! Thanks! This is great, _think_ I should be all set here - will let ya know. Blast from the past is right! Every now and then I go on daydream kicks...this happens to be one of those kicks. Appreciate it.

**Comment by ryanfantus** [comment]
Hey there! Happy new year! Hope all is well. Kind of a sidebar but - do you have any old daydream utilities or packages or anything floating around? I'd really like to try to get my hands on as much old stuff as possible, it's become quite the obsession lol.

**Comment by SnakeManPMC** [comment]
All the PMC stuff is here in our github, don't recall having anything else.
